### ISSUE TITLE
Medium Prio - Fix Character Realm Clear Bug

### ISSUE THREAD

**Issue by softwarecomplexity** [SanctuaryTeam/diablo4trading-fe#108]
# NOTE
This is specific to the live dev site https://dev.diablo4.trading/
Edit: Just discovered it on localhost too. Added second example.
# Overview
When clearing the realm selection (Eternal, Seasonal.. etc), the url suddenly flashes between `/undefined/undefined` and `/undefined` rapidly for a few seconds.
# Reproduction Steps
1. Open Search Items, Search Services, or My Services.
2. Click the realm selector input.
3. Click the x to clear the input.
Result: The URL will rapidly change with undefined paths
# Example: live site
![image](https://i.imgur.com/8oBPvmu.gif)
# Example 2: Localhost
![image](https://github.com/SanctuaryTeam/diablo4trading-fe/assets/60945689/81b5bfb5-4341-4c7d-92ec-bc181d76bfaf)

image

https://camo.githubusercontent.com/f8a60f3cb3d82adaa1c64c85e33c1c968452ea61747714f1fd727908fa22cbff/68747470733a2f2f692e696d6775722e636f6d2f386f4250766d752e676966

User Randomly Jumps Between Pages -
https://github.com/SanctuaryTeam/diablo4trading-fe/issues/92

**Comment by d4search** [comment]
This is fixed in #102

**Comment by Sparky-Kitty** [comment]
Working on getting strict checks working soon. Gonna be working with Devoder on this today.
