### ISSUE TITLE
Medium Prio - Re Directs For Website

### ISSUE THREAD

**Issue by softwarecomplexity** [SanctuaryTeam/diablo4trading-fe#109]
Task - 

Global Apply

Make sure users cannot see anything without logging in. 
Also add some MUI component that will give a gif animation of an arrow or make the text move around to indicate to the user where the login button is

https://github.com/SanctuaryTeam/diablo4trading-fe/issues/97

**Comment by d4search** [comment]
We have added some checks for security purposes, but we intend to allow users to view parts of the site without being logged in.

**Comment by Sparky-Kitty** [comment]
As of now, if someone attempts to buy a service while not being logged in, the snackbar already handles this: 


![Image](https://github.com/SanctuaryTeam/diablo4trading-fe/assets/60945689/30e72199-e64a-4810-9685-f4da5d987f63)
