### ISSUE TITLE
Bug: Clicking "x" to clear realm selector triggers odd infinite loop

### ISSUE THREAD

**Issue by Sparky-Kitty** [SanctuaryTeam/diablo4trading-fe#92]
# NOTE
This is specific to the live dev site https://dev.diablo4.trading/
Edit: Just discovered it on localhost too. Added second example.
# Overview
When clearing the realm selection (Eternal, Seasonal.. etc), the url suddenly flashes between `/undefined/undefined` and `/undefined` rapidly for a few seconds.
# Reproduction Steps
1. Open Search Items, Search Services, or My Services.
2. Click the realm selector input.
3. Click the x to clear the input.
Result: The URL will rapidly change with undefined paths
# Example: live site
![image](https://i.imgur.com/8oBPvmu.gif)
# Example 2: Localhost
![image](https://github.com/SanctuaryTeam/diablo4trading-fe/assets/60945689/81b5bfb5-4341-4c7d-92ec-bc181d76bfaf)

**Comment by softwarecomplexity** [comment]
It's because in the const handle clear we have the payload state set to and empty object. I will push forward a new commit to hopefully fix this.

**Comment by Sparky-Kitty** [comment]
> It's because in the const handle clear we have the payload state set to and empty object. I will push forward a new commit to hopefully fix this.

On develop, it looks like this
```tsx
    const handleClear = () => { 
         setQuery({ 
             ...query, 
             title: '', 
             tags: 0, 
         }); 
         setVisible(true); 
     };
```
It does reset the title, but not the tags. On Item-Listing it does have that payload reset though, like you mentioned.

Thanks for working on this!

**Comment by softwarecomplexity** [comment]
> > It's because in the const handle clear we have the payload state set to and empty object. I will push forward a new commit to hopefully fix this.
> 
> On develop, it looks like this
> 
> ```tsx
>     const handleClear = () => { 
>          setQuery({ 
>              ...query, 
>              title: '', 
>              tags: 0, 
>          }); 
>          setVisible(true); 
>      };
> ```
> 
> It does reset the title, but not the tags. On Item-Listing it does have that payload reset though, like you mentioned.
> 
> Thanks for working on this!

Add
```tsx
const handleClear = () => {
    setPayload(initialPayload);
    setVisible(true);
};
```

So that the the page doesnt freak out and just goes back to initial state when it was clicked or you can add a parameter to get the seasonal parameter so it resets to that.
